services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../:/app:delegated
    working_dir: /app
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    tty: true
    stdin_open: true
    command: ["bash"]
